# Generated by Django 3.2.16 on 2022-11-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('expdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.login')),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyname', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('post', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('certificate', models.FileField(upload_to='')),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.login')),
            ],
        ),
        migrations.CreateModel(
            name='medicineorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.medicine')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.user')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.pharmacy'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacks', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=20)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.pharmacy')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.user')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.pharmacy')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p3app.user')),
            ],
        ),
    ]
